version: '3.8'

services:
  flask_app:
    build: .
    ports:
      - "${PORT}:${PORT}"
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      SECRET_KEY: 0a0b331b2fb90155e70f8e9c897a0dd4
      SQLALCHEMY_DATABASE_URI: sqlite:///site.db
      SQLALCHEMY_TRACK_MODIFICATIONS: 'False'
      DEBUG: 'True'
      TESTING: 'False'
      PORT: 5000
    volumes:
      - .:/usr/src/app
    command: flask run --host=0.0.0.0 --port=${PORT}
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: flasksitebuilder_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

